// Code generated by mockery. DO NOT EDIT.

package usecase

import (
	model "github.com/mesirendon/contract-testing/consumer/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// mockUserGetter is an autogenerated mock type for the userGetter type
type mockUserGetter struct {
	mock.Mock
}

type mockUserGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUserGetter) EXPECT() *mockUserGetter_Expecter {
	return &mockUserGetter_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function with given fields: id
func (_m *mockUserGetter) GetUser(id int) (model.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) model.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockUserGetter_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type mockUserGetter_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - id int
func (_e *mockUserGetter_Expecter) GetUser(id interface{}) *mockUserGetter_GetUser_Call {
	return &mockUserGetter_GetUser_Call{Call: _e.mock.On("GetUser", id)}
}

func (_c *mockUserGetter_GetUser_Call) Run(run func(id int)) *mockUserGetter_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *mockUserGetter_GetUser_Call) Return(_a0 model.User, _a1 error) *mockUserGetter_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockUserGetter_GetUser_Call) RunAndReturn(run func(int) (model.User, error)) *mockUserGetter_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetToken provides a mock function with given fields: token
func (_m *mockUserGetter) SetToken(token string) {
	_m.Called(token)
}

// mockUserGetter_SetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetToken'
type mockUserGetter_SetToken_Call struct {
	*mock.Call
}

// SetToken is a helper method to define mock.On call
//   - token string
func (_e *mockUserGetter_Expecter) SetToken(token interface{}) *mockUserGetter_SetToken_Call {
	return &mockUserGetter_SetToken_Call{Call: _e.mock.On("SetToken", token)}
}

func (_c *mockUserGetter_SetToken_Call) Run(run func(token string)) *mockUserGetter_SetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockUserGetter_SetToken_Call) Return() *mockUserGetter_SetToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockUserGetter_SetToken_Call) RunAndReturn(run func(string)) *mockUserGetter_SetToken_Call {
	_c.Run(run)
	return _c
}

// newMockUserGetter creates a new instance of mockUserGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserGetter {
	mock := &mockUserGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
