resolve-type-alias: False
issue-845-fix: True
with-expecter: True
packages:
  github.com/mesirendon/contract-testing/provider/internal/handler:
    config:
      all: True
      inpackage: True
      outpkg: "{{.PackageName}}"
      dir: "{{.InterfaceDir}}"
      filename: "mock_{{.InterfaceName | snakecase }}_test.go"
      mockname: "mock{{ .InterfaceName | camelcase }}"
      with-expecter: True
      keeptree: False
